name: vayu_veda
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  http: ^1.3.0
  fluttertoast: ^8.2.1
  fl_chart: ^0.70.2
  intl: ^0.18.0
  syncfusion_flutter_gauges: ^29.1.33
  latlong2: ^0.9.1
  flutter_map: ^5.0.0
  flutter_map_marker_popup: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_bg.jpeg
    - assets/images/logo.png
    - assets/images/air_pollution.png
    - assets/images/air_pollution_1.png
    - assets/images/air_pollution_2.png

